### ISSUE TITLE
[BUG] 导入后报错，缺少Unit, Pool, Runner

### ISSUE THREAD

**Issue by floatingsnowflake** [AIO-GAME/Unity.Timer#7]
![image](https://github.com/AIO-GAME/Unity.Timer/assets/50739568/68c4412d-501d-48d0-8c14-e1756d77d0f8)

**Comment by xinansky** [comment]
好的,收到,这是缺少其他依赖库导致, 可以暂时尝试加上 `manifest.json` 文件内添加 "com.aio.runner": "https://github.com/AIO-GAME/Unity.Runner.git#1.0.0-preview"

**Comment by xinansky** [comment]
或者使用 `openupm` Packages Manifest [参考地址](https://github.com/AIO-GAME/Unity.Timer?tab=readme-ov-file#-%E5%AE%89%E8%A3%85)
```
{
  "dependencies": {
    "com.aio.timer": "1.0.1-preview"
  },
  "scopedRegistries": [
    {
      "name": "package.openupm.com",
      "url": "https://package.openupm.com",
      "scopes": [
        "com.aio.timer",
        "com.aio.runner"
      ]
    }
  ]
}
```

**Comment by floatingsnowflake** [comment]
解决了谢谢，重新添加就好了
